name: social_media
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  form_field_validator: ^1.1.0
  google_fonts: ^2.3.1
  http: ^0.13.4
  image_picker: ^0.8.4+9
  permission_handler: ^9.2.0
  pin_code_fields: ^7.3.0
  photo_manager: ^2.0.1
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0
  timeago: ^3.2.2
  cached_network_image: ^3.2.0
  socket_io_client: ^1.0.2
  equatable: ^2.0.3
  get_it: ^7.2.0
  antdesign_icons: ^0.0.3
  tinycolor2: ^2.0.1
  logger: ^1.1.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  modal_bottom_sheet: ^2.0.1
  flutter_screenutil: ^5.5.3+2
  firebase_core: ^1.18.0 # required for initializing firebase app
  firebase_messaging: ^11.4.2 # required for sending/receiving messages through FCM
  flutter_local_notifications: ^9.5.3+1 # required to show chat notifications
  faker: ^2.0.0
  # stream_chat: ^4.1.0
  # stream_chat_flutter: ^4.2.0
  # stream_chat_persistence: ^4.1.0
  # stream_chat_localizations: ^3.1.0
  # flutter_local_notifications: ^9.0.0
  yaml: ^3.1.0
  uuid: ^3.0.5
  streaming_shared_preferences: ^2.0.0
  lottie: ^1.2.1
  collection: ^1.15.0
  sentry_flutter: ^6.5.0
  persistent_bottom_nav_bar: ^4.0.2
  google_nav_bar: ^5.0.6
  bottom_navy_bar: ^6.0.0
  encrypt: ^5.0.1
  photo_view: ^0.14.0
  lazy_load_scrollview: ^1.3.0
  flutter_custom_dialog: ^1.2.0
  video_player: ^2.4.5
  file_picker: ^4.6.1
  modal_side_sheet: ^0.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.6.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/videos/

flutter_intl: # Add this line
  enabled: true # Add this line
  class_name: S # Add this line
  main_locale: vi # Add this line
  arb_dir: lib/commons/l10n/translation # Add this line
  output_dir: lib/commons/l10n/generated # Add this line
  use_deferred_loading: true
